In [3]:
import json
import pandas as pd
from pandas.io.json import json_normalize
import requests


def to_string(s):
    try:
        return str(s)
    except:
        # Change the encoding type if needed
        return s.encode('utf-8')


def reduce_item(key, value):
    global reduced_item

    # Reduction Condition 1
    if type(value) is list:
        i = 0
        for sub_item in value:
            reduce_item(key + '_' + to_string(i), sub_item)
            i = i + 1

    # Reduction Condition 2
    elif type(value) is dict:
        sub_keys = value.keys()
        for sub_key in sub_keys:
            reduce_item(key + '_' + to_string(sub_key), value[sub_key])

    # Base Condition
    else:
        reduced_item[to_string(key)] = to_string(value)

proxies = {
  'http': 'proxy_addres1',
  'https': 'proxy_addres2',
}

url = 'https://data.dublinked.ie/cgi-bin/rtpi/routeinformation?routeid=1&operator=BE&format=json'


response = requests.get(url, proxies=proxies)

data = response.json()
data = [data]


processed_data = []
header = []
for item in data:
    reduced_item = {}
    reduce_item('', item)
    header += reduced_item.keys()
    processed_data.append(reduced_item)


df = pd.DataFrame.from_dict(json_normalize(processed_data), orient='columns')

df

,_errorcode,_errormessage,_numberofresults,_results_0_destination,_results_0_destinationlocalized,_results_0_lastupdated,_results_0_operator,_results_0_origin,_results_0_originlocalized,_results_0_stops_0_displaystopid,...,_results_1_stops_9_fullnamelocalized,_results_1_stops_9_latitude,_results_1_stops_9_longitude,_results_1_stops_9_operators_0_name,_results_1_stops_9_operators_0_routes_0,_results_1_stops_9_shortname,_results_1_stops_9_shortnamelocalized,_results_1_stops_9_stopid,_route,_timestamp
0,0,,2,Dublin,Dublin,16/10/2017 10:50:22,BE,Belfast,Belfast,135001,...,,54.34642,-6.27154,BE,1,Banbridge,Droichead na Banna,156121,1,17/10/2017 14:10:32